
apiClients:
  alpaca:
    base_url: https://paper-api.alpaca.markets/v2
    data_url: https://data.alpaca.markets/v2
    api_key: PK6SM5ZSKB1JNZX6X016
    api_secret: YHQ5AeWimtiag7h2Nj7Iczqn2tyFwsEcwIaV9XTa
  alphavantage:
    base_url: https://www.alphavantage.co
    api_key: 6IOTMW5JJX34E1FZ

marketData:
  state_table: test_data.ticker_state
  feeds:
    feed:
      target_table: test_data.market_feed
    news_sentiment:
      target_table: test_data.sentiment_feed
    indicator:
      target_table: test_data.indicator_feed
    economic:
      target_table: test_data.economic_feed
  symbols:
    - AAPL
    - ABNB
    - ADBE
    - AI
    - AMD
    - AMZN
    - ASML
    - BEAM
    - BKI
    - CRSP
    - DDOG
    - DOCN
    - ENPH
    - GME
    - GOOGL
    - HCP
    - LCID
    - META
    - MNDT
    - MSFT
    - NET
    - NTLA
    - NVDA
    - NXPI
    - PANW
    - PLTR
    - PSTG
    - QCOM
    - SHOP
    - SMAR
    - SQ
    - TOST
    - TSLA
    - TSM
    - TWLO
    - UBER
    - UPST
    - UIS
    - EA
    - COIN
    - SNAP
    - INTC
    - NFLX
    - TWTR
    - PYPL
    - HEAR
    - RRC
  
database:
  host: tp1pzsvw6b9gb6v.cz6kbxppcrig.us-west-2.rds.amazonaws.com
  database: tradingbotDB
  username: tradingbot
  password: trading123

model:
  save_path: /etc/tradingbot_modeler/model.pickle
  archive_path: /etc/tradingbot_modeler/archive
  api:
    base_url: http://localhost:8000