--CREATE TABLE test_data.ml_input AS
SELECT
    feed.symbol,
    -- TARGETS
    LEAD(trend_ema_slow, 30*500) OVER (PARTITION BY indicators.symbol ORDER BY agg_ts) future30_ema,
    -- FEATURES
    open_price,
    high_price,
    low_price,
    close_price,
    volume,
    COALESCE(ticker_sentiment, 0.0) ticker_sentiment,
    COALESCE(relevance_score, 0.0) relevance_score,
    volume_adi,
    volume_obv,
    volume_cmf,
    volume_fi,
    volume_em,
    volume_sma_em,
    volume_vpt,
    volume_vwap,
    volume_mfi,
    volume_nvi,
    volatility_bbm,
    volatility_bbh,
    volatility_bbl,
    volatility_bbw,
    volatility_bbp,
    volatility_bbhi,
    volatility_bbli,
    volatility_kcc,
    volatility_kch,
    volatility_kcl,
    volatility_kcw,
    volatility_kcp,
    volatility_kchi,
    volatility_kcli,
    volatility_dcl,
    volatility_dch,
    volatility_dcm,
    volatility_dcw,
    volatility_dcp,
    volatility_atr,
    volatility_ui,
    trend_macd,
    trend_macd_signal,
    trend_macd_diff,
    trend_sma_fast,
    trend_sma_slow,
    trend_ema_fast,
    trend_ema_slow,
    trend_vortex_ind_pos,
    trend_vortex_ind_neg,
    trend_vortex_ind_diff,
    trend_trix,
    trend_mass_index,
    trend_dpo,
    trend_kst,
    trend_kst_sig,
    trend_kst_diff,
    trend_ichimoku_conv,
    trend_ichimoku_base,
    trend_ichimoku_a,
    trend_ichimoku_b,
    trend_stc,
    trend_adx,
    trend_adx_pos,
    trend_adx_neg,
    trend_cci,
    trend_visual_ichimoku_a,
    trend_visual_ichimoku_b,
    trend_aroon_up,
    trend_aroon_down,
    trend_aroon_ind,
    trend_psar_up,
    trend_psar_down,
    trend_psar_up_indicator,
    trend_psar_down_indicator,
    momentum_rsi,
    momentum_stoch_rsi,
    momentum_stoch_rsi_k,
    momentum_stoch_rsi_d,
    momentum_tsi,
    momentum_uo,
    momentum_stoch,
    momentum_stoch_signal,
    momentum_wr,
    momentum_ao,
    momentum_roc,
    momentum_ppo,
    momentum_ppo_signal,
    momentum_ppo_hist,
    momentum_pvo,
    momentum_pvo_signal,
    momentum_pvo_hist,
    momentum_kama,
    others_dr,
    others_dlr,
    others_cr,
    COALESCE(treasury_yield_10_yr, LAG(treasury_yield_10_yr, 1) OVER (ORDER BY metric_ts)) treasury_yield_10_yr,
    COALESCE(federal_fund_rate, LAG(federal_fund_rate, 1) OVER (ORDER BY metric_ts)) federal_fund_rate,
    COALESCE(cpi, LAG(cpi, 1) OVER (ORDER BY metric_ts)) cpi,
    COALESCE(inflation_expectation, LAG(inflation_expectation, 1) OVER (ORDER BY metric_ts)) inflation_expectation,
    COALESCE(consumer_sentiment, LAG(consumer_sentiment, 1) OVER (ORDER BY metric_ts)) consumer_sentiment,
    COALESCE(retail_sales, LAG(retail_sales, 1) OVER (ORDER BY metric_ts)) retail_sales,
    COALESCE(durable_goods_orders, LAG(durable_goods_orders, 1) OVER (ORDER BY metric_ts)) durable_goods_orders,
    COALESCE(unemployment_rate, LAG(unemployment_rate, 1) OVER (ORDER BY metric_ts)) unemployment_rate,
    COALESCE(nonfarm_payroll, LAG(nonfarm_payroll, 1) OVER (ORDER BY metric_ts)) nonfarm_payroll,
    COALESCE(real_gdp, LAG(real_gdp, 1) OVER (ORDER BY metric_ts)) real_gdp,
    COALESCE(real_gdp_per_capita, LAG(real_gdp_per_capita, 1) OVER (ORDER BY metric_ts)) real_gdp_per_capita
FROM test_data.market_feed AS feed
JOIN test_data.indicator_feed indicators
    ON feed.symbol = indicators.symbol
    AND feed.bar_ts = indicators.agg_ts
LEFT JOIN test_data.sentiment_feed sentiment
    ON feed.symbol = sentiment.symbol
    AND feed.bar_ts = sentiment.pub_ts
LEFT JOIN test_data.economic_feed econ
    ON DATE(bar_ts) = DATE(econ.metric_ts)
WHERE feed.bar_ts >= '2021-08-01' AND feed.bar_ts < '2021-11-01'
AND indicators.agg_ts >= '2021-08-01' AND indicators.agg_ts < '2021-11-01';


